### ISSUE TITLE
wp-config management

### ISSUE THREAD

**Issue by saplingdigital** [saplingdigitalltd/fertilizer#1]
Managing wp-configs between team members is painful. 
Yeopress tracks the config file but ignores the `local-config.php`file. Consider moving all local config (for any environment) here.

Alternatively, look at a more comprehensive environment setup.

**Comment by guyroutledge** [comment]
Running the yeopress script with the `--advanced` flag provides the option to create the local-config and add wp-config to the .gitignore. That should do for now.
